volumes:
  postgres-data:
    external: true
  jwtdown-db-data:
    external: true

services:
  fastapi:
    build:
      context: ./wandrrr
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./wandrrr:/app
    environment:
      SIGNING_KEY: secret_key
      DATABASE_URL: postgresql://wandrrr:password@postgres/wandrrr
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wandrrr
      POSTGRES_USER: wandrrr
      POSTGRES_PASSWORD: password

    ports:
      - 15432:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_WANDRRR_API_HOST: http://localhost:8000
